version: '2'

services:
  bitcore:
    container_name: bitcore
    build: .
    restart: always
    environment:
      - TZ=Europe/London
      - NETWORK=testnet
    ports:
      - 3001:3001
      - 8333
    volumes:
      - data:/src/data
      - node_modules:/usr/local/lib/node_modules

volumes:
  data:
  node_modules:
